-- Baseline: schema exatamente como o Hibernate (ddl-auto=update) o deixou antes desta
-- migracao assumir o controle (ver PLANO_ACAO_COMPLETO.md, item 5). Extraido via pg_dump
-- --schema-only do banco de desenvolvimento e adaptado para SQL puro.

CREATE TABLE account_payable (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(38,2),
    description character varying(255),
    due_date date,
    payment_date date,
    status character varying(255),
    supplier_id bigint,
    CONSTRAINT account_payable_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'OVERDUE'::character varying])::text[])))
);

CREATE TABLE account_receivable (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(38,2),
    description character varying(255),
    due_date date,
    receipt_date date,
    status character varying(255),
    person_id bigint,
    CONSTRAINT account_receivable_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RECEIVED'::character varying, 'OVERDUE'::character varying])::text[])))
);

CREATE TABLE address (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nbhd character varying(255),
    number character varying(255),
    street character varying(255),
    city_id bigint
);

CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    role character varying(255)
);

CREATE TABLE cash_movement (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(38,2),
    date timestamp(6) without time zone,
    description character varying(255),
    type character varying(255),
    cash_register_id bigint,
    user_id bigint,
    CONSTRAINT cash_movement_type_check CHECK (((type)::text = ANY ((ARRAY['INCOME'::character varying, 'EXPENSE'::character varying])::text[])))
);

CREATE TABLE cash_register (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    closing_balance numeric(38,2),
    closing_time timestamp(6) without time zone,
    is_open boolean NOT NULL,
    opening_balance numeric(38,2),
    opening_time timestamp(6) without time zone,
    closed_by_user_id bigint,
    opened_by_user_id bigint
);

CREATE TABLE category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);

CREATE TABLE city (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255),
    state_id bigint
);

CREATE TABLE person (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    cpf character varying(255),
    email character varying(255),
    name character varying(255),
    phone character varying(255),
    address_id bigint
);

CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    code character varying(255),
    min_storage numeric(38,2),
    name character varying(255),
    package_quantity numeric(38,2),
    price numeric(38,2),
    purchase_unit character varying(255),
    sell_price numeric(38,2),
    storage numeric(38,2),
    tipo character varying(255),
    category_id bigint,
    CONSTRAINT product_purchase_unit_check CHECK (((purchase_unit)::text = ANY ((ARRAY['G'::character varying, 'KG'::character varying, 'ML'::character varying, 'L'::character varying, 'UN'::character varying, 'DUZIA'::character varying])::text[]))),
    CONSTRAINT product_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['INSUMO'::character varying, 'PRODUTO_FINAL'::character varying, 'PRODUTO_INTERMEDIARIO'::character varying])::text[])))
);

CREATE TABLE production_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date timestamp(6) without time zone,
    notes character varying(255),
    quantity integer,
    status character varying(255),
    final_product_id bigint,
    CONSTRAINT production_order_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'FINISHED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE purchase (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date,
    total numeric(38,2),
    supplier_id bigint
);

CREATE TABLE purchase_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity integer,
    unit_price numeric(38,2),
    product_id bigint,
    purchase_id bigint
);

CREATE TABLE sale (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date timestamp(6) without time zone,
    discount integer,
    payment_method character varying(255),
    total numeric(38,2),
    person_id bigint
);

CREATE TABLE sell_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity numeric(38,2),
    unit_price numeric(38,2),
    product_id bigint,
    sale_id bigint
);

CREATE TABLE stock_movement (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date timestamp(6) without time zone,
    description character varying(255),
    quantity numeric(38,2),
    type character varying(255),
    product_id bigint,
    CONSTRAINT stock_movement_type_check CHECK (((type)::text = ANY ((ARRAY['ENTRY'::character varying, 'EXIT'::character varying])::text[])))
);

CREATE TABLE supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    cnpj character varying(255),
    email character varying(255),
    name character varying(255),
    phone character varying(255),
    registration character varying(255),
    address_id bigint
);

CREATE TABLE technical_sheet (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desired_margin_percent numeric(38,2),
    labour_cost_percent numeric(38,2),
    name character varying(255),
    rendimento integer,
    variable_expenses_percent numeric(38,2),
    final_product_id bigint
);

CREATE TABLE technical_sheet_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity numeric(38,2),
    unit character varying(255),
    raw_material_id bigint,
    technical_sheet_id bigint,
    CONSTRAINT technical_sheet_item_unit_check CHECK (((unit)::text = ANY ((ARRAY['G'::character varying, 'KG'::character varying, 'ML'::character varying, 'L'::character varying, 'UN'::character varying, 'DUZIA'::character varying])::text[])))
);

CREATE TABLE uf (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255),
    uf character varying(255)
);

ALTER TABLE purchase_item ADD CONSTRAINT fk1mncc5yaore1sibgpj3jc4a7u FOREIGN KEY (purchase_id) REFERENCES purchase(id);
ALTER TABLE product ADD CONSTRAINT fk1mtsbur82frn64de7balymq9s FOREIGN KEY (category_id) REFERENCES category(id);
ALTER TABLE production_order ADD CONSTRAINT fk29coynrutxmvbp0hr4ylm4gl9 FOREIGN KEY (final_product_id) REFERENCES product(id);
ALTER TABLE sale ADD CONSTRAINT fk5y1pg8orekk5ivcwd41gbvssn FOREIGN KEY (person_id) REFERENCES person(id);
ALTER TABLE sell_item ADD CONSTRAINT fk7bw23i2yiml6l6uyk1v20exr8 FOREIGN KEY (sale_id) REFERENCES sale(id);
ALTER TABLE cash_movement ADD CONSTRAINT fk8f4ypvem68ju53um67tw0751p FOREIGN KEY (cash_register_id) REFERENCES cash_register(id);
ALTER TABLE account_receivable ADD CONSTRAINT fk8g50fkm6re2v3nfuow4vcxwd3 FOREIGN KEY (person_id) REFERENCES person(id);
ALTER TABLE purchase ADD CONSTRAINT fk8omm6fki86s9oqk0o9s6w43h5 FOREIGN KEY (supplier_id) REFERENCES supplier(id);
ALTER TABLE supplier ADD CONSTRAINT fk95a8oipih48obtbhltjy7hgvb FOREIGN KEY (address_id) REFERENCES address(id);
ALTER TABLE technical_sheet_item ADD CONSTRAINT fkfnjshi8xi265g88nnijjq2jap FOREIGN KEY (technical_sheet_id) REFERENCES technical_sheet(id);
ALTER TABLE cash_register ADD CONSTRAINT fkgc06r6v2dg9khyj1915x7ptog FOREIGN KEY (opened_by_user_id) REFERENCES app_user(id);
ALTER TABLE account_payable ADD CONSTRAINT fkhghh6vxy7kin8258fmp10ai8u FOREIGN KEY (supplier_id) REFERENCES supplier(id);
ALTER TABLE cash_movement ADD CONSTRAINT fkhpitq86t0jjtsqp0gurr2wjtu FOREIGN KEY (user_id) REFERENCES app_user(id);
ALTER TABLE technical_sheet ADD CONSTRAINT fkih8plep2xt6qxub7md02pmkj5 FOREIGN KEY (final_product_id) REFERENCES product(id);
ALTER TABLE city ADD CONSTRAINT fkiuvcfyl5ukvqiwbkgtqhopig0 FOREIGN KEY (state_id) REFERENCES uf(id);
ALTER TABLE sell_item ADD CONSTRAINT fkjdwr21vlhof9rod1wkqd2r72p FOREIGN KEY (product_id) REFERENCES product(id);
ALTER TABLE person ADD CONSTRAINT fkk7rgn6djxsv2j2bv1mvuxd4m9 FOREIGN KEY (address_id) REFERENCES address(id);
ALTER TABLE cash_register ADD CONSTRAINT fkn5fjbo610jbwqwh0jnbfukuy FOREIGN KEY (closed_by_user_id) REFERENCES app_user(id);
ALTER TABLE technical_sheet_item ADD CONSTRAINT fkpcwlo0xaq1y8fki38mho2ioqk FOREIGN KEY (raw_material_id) REFERENCES product(id);
ALTER TABLE address ADD CONSTRAINT fkpo044ng5x4gynb291cv24vtea FOREIGN KEY (city_id) REFERENCES city(id);
ALTER TABLE stock_movement ADD CONSTRAINT fkq63e7y5l2pnh2tt2lvxlquvbf FOREIGN KEY (product_id) REFERENCES product(id);
ALTER TABLE purchase_item ADD CONSTRAINT fkq69apam78dbi0cggl37ge6auf FOREIGN KEY (product_id) REFERENCES product(id);
