-- Item 7: lock otimista no produto (evita venda/compra concorrente gerar estoque negativo).
ALTER TABLE product ADD COLUMN version bigint NOT NULL DEFAULT 0;

-- Item 8: chave de idempotencia em venda e compra (reenvio do mesmo formulario nao duplica).
ALTER TABLE sale ADD COLUMN idempotency_key character varying(255);
ALTER TABLE sale ADD CONSTRAINT uk_sale_idempotency_key UNIQUE (idempotency_key);

ALTER TABLE purchase ADD COLUMN idempotency_key character varying(255);
ALTER TABLE purchase ADD CONSTRAINT uk_purchase_idempotency_key UNIQUE (idempotency_key);

-- Item 10: auditoria de operacoes financeiras/sensiveis.
CREATE TABLE activity_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora timestamp(6) without time zone NOT NULL,
    acao character varying(255) NOT NULL,
    entidade character varying(255) NOT NULL,
    entidade_id bigint,
    detalhes character varying(1000),
    usuario_id bigint,
    usuario_nome character varying(255)
);

CREATE INDEX idx_activity_log_data_hora ON activity_log (data_hora DESC);
